name: Online Packager

on:
  workflow_dispatch:
 #   inputs:
 #     configURL:
 #       description: 'Direct URL to config.xml'
 #     romURL:
 #       description: 'Direct URL to ROM'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Install NDK
#        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=$ANDROID_SDK_ROOT

 #     - name: Fetch Config
 #       run: curl -L# "${{ github.event.inputs.configURL }}" > ./app/src/main/res/values/config.xml

 #     - name: Fetch Assets
 #       run: |
 #         mkdir -p ./app/src/main/res/raw/
 #         curl -L# "${{ github.event.inputs.romURL }}" > ./app/src/main/res/raw/rom

      - name: convert icon to png
        run: if  test -f ./app/icon.jpg ; then convert ./app/icon.jpg -resize 512x512 ./app/icon.png; elif test -f ./app/icon.jpeg ; then convert ./app/icon.jpeg -resize 512x512 ./app/icon.png; fi
    #  - name: remove current icons
     #    run: rm -f ./app/src/main/res/drawable-hdpi/ic_launcher.png /home/runner/work/dolphin/dolphin/Source/Android/app/src/main/res/drawable-xhdpi/ic_launcher.png /home/runner/work/dolphin/dolphin/Source/Android/app/src/main/res/drawable-xxhdpi/ic_launcher.png /home/runner/work/dolphin/dolphin/Source/Android/app/src/main/res/drawable-xxxhdpi/ic_launcher.png /home/runner/work/dolphin/dolphin/Source/Android/app/src/main/res/drawable-mdpi/ic_launcher.png /home/runner/work/dolphin/dolphin/Source/Android/app/src/main/res/drawable-ldpi/ic_launcher.png
      - name: convert for hdpi
        run: convert ./app/icon.png -resize 72x72 ./app/src/main/res/mipmap-hdpi/icon.png
      - name: convert for xhdpi
        run: convert ./app/icon.png -resize 96x96 ./app/src/main/res/mipmap-xhdpi/icon.png
      - name: convert for xxhdpi
        run: convert ./app/icon.png -resize 144x144 ./app/src/main/res/mipmap-xxhdpi/icon.png
      - name: convert for xxxhdpi
        run: convert ./app/icon.png -resize 192x192 ./app/src/main/res/mipmap-xxxhdpi/icon.png
      - name: convert for mdpi
        run: convert ./app/icon.png -resize 48x48 ./app/src/main/res/mipmap-mdpi/icon.png
      
      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace
          
      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ludere-${{ steps.date.outputs.date }}
          release_name: Ludere ${{ steps.date.outputs.date }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/release/app-universal-release.apk
          asset_name: ludere.apk
          asset_content_type: application/apk
